services:
  verification_be:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
    command: npm start
